This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file D:/_HSE/_ARBEIT/eclipse-cpp-galileo-SR1-win32/Workspace2/MASTER_THESIS_PRJ/doc/MasterThesis/MasterThesis/Master_Thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Master_Thesis.acn....done (154 entries accepted, 0 rejected).
Sorting entries....done (1181 comparisons).
Generating output file Master_Thesis.acr....done (196 lines written, 0 warnings).
Output written in Master_Thesis.acr.
Transcript written in Master_Thesis.alg.
