This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file D:/_HSE/_ARBEIT/eclipse-cpp-galileo-SR1-win32/Workspace2/MASTER_THESIS_PRJ/doc/interimReport/InterimReport/Interim_Report.ist..............done (14 attributes redefined, 0 ignored).
Scanning input file Interim_Report.acr....done (78 entries accepted, 0 rejected).
Sorting entries....done (524 comparisons).
Generating output file Interim_Report.acn....done (61 lines written, 0 warnings).
Output written in Interim_Report.acn.
Transcript written in Interim_Report.alg.
